spring:
  application:
    name: ChatService
  data:
    mongodb:
      uri: mongodb+srv://deva:deva123@atlascluster.inazn0l.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
      database: TravelBuddy

server:
  port: 9002

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: https://travelbuddy-servicediscovery-production.up.railway.app/eureka/
